name: Publish package

on:
    release:
        types: [released, prereleased]

jobs:
    Publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
            - name: Setup Action
              uses: actions/checkout@v7

            - name: Setup PNPM
              uses: pnpm/action-setup@v6

            - name: Setup Node.js
              uses: actions/setup-node@v7
              with:
                  registry-url: https://registry.npmjs.org/
                  node-version: "latest"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build
              run: pnpm exec turbo build --filter="cn-apps"

            - name: Sync version
              working-directory: package/cn-apps
              run: pnpm version --no-git-tag-version ${{ github.ref_name }}

            - name: Publish
              run: pnpm --filter "./package/cn-apps" publish --provenance --access public --no-git-checks --tag ${{ github.event.release.prerelease && 'beta' || 'latest' }}
